% This is the file that reads the log files generated by the strip chart
% program (specifically, the .log files that contained the translated
% inputs).

close all;
clear all;

% Constant values

filetype = '*.log'; % the supported file types
numberOfValues = 39; % the number of checkboxes to be made available
heightVal = 1/(numberOfValues+1); % the divider

% Opening the desired log file (this could be updated to also get .bat
% files).

[FileName,PathName] = uigetfile(filetype,'Select the logfile to plot.');
filename = strcat(PathName,FileName) % making note of the filename including path

LogData = csvread(filename); % Reading the csv file

% Creating the checkbox figure (Need to add callback functions)

Checks.f = figure('Position', [100 100 752 250],'toolbar','none');
set(Checks.f,'Units','Normalized','OuterPosition',[0.25 0 0.5 1]);
for i = 1:numberOfValues % initializing the checkboxes
    h.c(i) = uicontrol('style','checkbox','units','normalized',...
        'position',[0.3 heightVal*(numberOfValues-i+1) 0.4 heightVal],...
        'string',i);
end
h.c(numberOfValues+1) = uicontrol('units','normalized',...
    'position',[0.3 0 0.4 heightVal],'string','Continue');
    % adding the continue button